In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as ny # linear algebra
import pandas as ps # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
dataset = ps.DataFrame([[8, 9, 4, 1], [5, 4, 7, 1], [5, 4, 3, 0], [3, 6, 2, 0]], columns = ['Cgpa', 'ProfileScore', 'InterviewScore', 'Selection'])
dataset

Cgpa  ProfileScore  InterviewScore  Selection
0     8             9               4          1
1     5             4               7          1
2     5             4               3          0
3     3             6               2          0

In [3]:
def initializeParameters(layer_dims):
  
  ny.random.seed(3)
  parameters = {}
  layers = len(layer_dims)         

  for layer in range(1, layers):

    parameters['W' + str(layer)] = ny.ones((layer_dims[layer-1], layer_dims[layer]))*0.1
    parameters['b' + str(layer)] = ny.zeros((layer_dims[layer], 1))
      

  return parameters

In [4]:
# Utility Functions
def sigmoid(Z):
  
  A = 1/(1+ny.exp(-Z))

  return A

In [5]:
def linearForward(A_prev, W, b):
  
  Z = ny.dot(W.T, A_prev) + b

  A = sigmoid(Z)
  
  return A

In [6]:
# L-layer feed forward

def lLayerForward(x, parameters):

  A = x
  Layers = len(parameters) // 2                  # number of layers in the neural network
  
  for layer in range(1, Layers + 1):
    Aprev = A 
    Wl = parameters['W' + str(layer)]
    bl = parameters['b' + str(layer)]
#     print("A"+str(l-1)+": ", A_prev)
#     print("W"+str(l)+": ", Wl)
#     print("b"+str(l)+": ", bl)
#     print("--"*20)

    A = linearForward(Aprev, Wl, bl)
#     print("A"+str(l)+": ", A)
#     print("**"*20)
          
  return A, Aprev

In [7]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [8]:
X = dataset[['Cgpa', 'ProfileScore']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = dataset[['Selection']].values[0][0]

# Parameter initialization
parameters = initializeParameters([2,2,1])

y_hat,A1 = lLayerForward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*ny.log(y_hat) - (1-y)*ny.log(1-y_hat))

parameters

Loss for this student -  0.6121641007486958


{'W1': array([[0.10000479, 0.10000538],
        [0.10000479, 0.10000538]]),
 'b1': array([[5.98175564e-07],
        [5.98175564e-07]]),
 'W2': array([[0.10003871],
        [0.10003871]]),
 'b2': array([[0.10008449]])}

In [9]:
X = dataset[['Cgpa', 'ProfileScore']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = dataset[['Selection']].values[1][0]

y_hat,A1 = lLayerForward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*ny.log(y_hat) - (1-y)*ny.log(1-y_hat))

parameters

Loss for this student -  0.5793041781681331


{'W1': array([[0.10000931, 0.100009  ],
        [0.10000931, 0.100009  ]]),
 'b1': array([[1.50240050e-06],
        [1.50239845e-06]]),
 'W2': array([[0.10006997],
        [0.10006997]]),
 'b2': array([[0.10011394]])}

In [10]:
X = dataset[['Cgpa', 'ProfileScore']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = dataset[['Selection']].values[2][0]

y_hat,A1 = lLayerForward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*ny.log(y_hat) - (1-y)*ny.log(1-y_hat))

parameters

Loss for this student -  0.8216777921637785


{'W1': array([[0.10000355, 0.10000439],
        [0.10000355, 0.10000439]]),
 'b1': array([[3.50662990e-07],
        [3.50659598e-07]]),
 'W2': array([[0.10003014],
        [0.10003014]]),
 'b2': array([[0.09997411]])}

In [11]:
X = dataset[['Cgpa', 'ProfileScore']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = dataset[['Selection']].values[3][0]

y_hat,A1 = lLayerForward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*ny.log(y_hat) - (1-y)*ny.log(1-y_hat))

parameters

Loss for this student -  0.8215666059185625


{'W1': array([[0.10000009, 0.09999749],
        [0.10000009, 0.09999749]]),
 'b1': array([[-8.00541179e-07],
        [-8.00540875e-07]]),
 'W2': array([[0.0999903],
        [0.0999903]]),
 'b2': array([[0.09993428]])}

In [12]:
# epochs implementation

parameters = initializeParameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(dataset.shape[0]):

    X = dataset[['Cgpa', 'ProfileScore']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = dataset[['Selection']].values[j][0]

    # Parameter initialization


    y_hat,A1 = lLayerForward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*ny.log(y_hat) - (1-y)*ny.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',ny.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7086781692497923
Epoch -  2 Loss -  0.6975461225583588
Epoch -  3 Loss -  0.6975446744202698
Epoch -  4 Loss -  0.69754322679371
Epoch -  5 Loss -  0.6975417796784794
Epoch -  6 Loss -  0.6975403330743801
Epoch -  7 Loss -  0.6975388869812127
Epoch -  8 Loss -  0.6975374413987785
Epoch -  9 Loss -  0.6975359963268787
Epoch -  10 Loss -  0.6975345517653148
Epoch -  11 Loss -  0.6975331077138881
Epoch -  12 Loss -  0.6975316641724003
Epoch -  13 Loss -  0.6975302211406531
Epoch -  14 Loss -  0.6975287786184481
Epoch -  15 Loss -  0.697527336605587
Epoch -  16 Loss -  0.6975258951018719
Epoch -  17 Loss -  0.6975244541071045
Epoch -  18 Loss -  0.6975230136210873
Epoch -  19 Loss -  0.6975215736436219
Epoch -  20 Loss -  0.697520134174511
Epoch -  21 Loss -  0.6975186952135567
Epoch -  22 Loss -  0.6975172567605612
Epoch -  23 Loss -  0.6975158188153275
Epoch -  24 Loss -  0.6975143813776578
Epoch -  25 Loss -  0.6975129444473548
Epoch -  26 Loss -  0.6975115080242213

{'W1': array([[0.09999243, 0.09986087],
        [0.09999255, 0.09986096]]),
 'b1': array([[-4.14210556e-05],
        [-4.14167291e-05]]),
 'W2': array([[0.09941566],
        [0.09941575]]),
 'b2': array([[0.09935976]])}

In [13]:
import tensorflow
from tensorflow import keras
from keras  import Sequential
from keras.layers import Dense

In [14]:
model = Sequential()
model.add(Dense(2, activation = 'sigmoid', input_dim = 2))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


2022-12-27 23:59:25.691641: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [15]:
model.get_weights()

[array([[-0.5299088, -0.8004077],
        [-1.0608083, -1.2019454]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.3785155 ],
        [-0.47647554]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
newweights = [ny.array([[0.1, 0.1],
                        [0.1, 0.1]], dtype = ny.float32),
             ny.array([0., 0.], dtype = ny.float32),
             ny.array([[0.1],
                      [0.1]], dtype = ny.float32),
             ny.array([0.], dtype = ny.float32)]

In [17]:
model.set_weights(newweights)

In [18]:
optimizer  = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'binary_crossentropy', optimizer = optimizer)
model.fit(dataset.iloc[:, 0: 2].values, dataset['Selection'].values,epochs = 50, verbose = 1, batch_size = 1)

2022-12-27 23:59:26.532922: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6931
Epoch 2/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6928
Epoch 3/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6928
Epoch 4/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6928
Epoch 5/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6927
Epoch 6/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6926
Epoch 7/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6928
Epoch 8/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6926
Epoch 9/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6925
Epoch 10/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6925
Epoch 11/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6925
Epoch 12/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6927
Epoch 13/50
4/4 [==============================] - 0s 2ms/step - loss: 0.