In [1]:
import  numpy as ny

texts = ["War Against Corruption", "Be Healthy Be Fit", "Achieve & uprise your career", "Holiday vacation in Los Angeles", "Good reputed job in international company",
        "Travelling in yacht", "Fifa wc final", "Earn in high scale", "Visit to 7 wonderland", "sea diving"]

In [2]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token = "winner")

In [3]:
tokenizer.fit_on_texts(texts)

In [4]:
tokenizer.word_index

{'winner': 1,
 'in': 2,
 'be': 3,
 'war': 4,
 'against': 5,
 'corruption': 6,
 'healthy': 7,
 'fit': 8,
 'achieve': 9,
 'uprise': 10,
 'your': 11,
 'career': 12,
 'holiday': 13,
 'vacation': 14,
 'los': 15,
 'angeles': 16,
 'good': 17,
 'reputed': 18,
 'job': 19,
 'international': 20,
 'company': 21,
 'travelling': 22,
 'yacht': 23,
 'fifa': 24,
 'wc': 25,
 'final': 26,
 'earn': 27,
 'high': 28,
 'scale': 29,
 'visit': 30,
 'to': 31,
 '7': 32,
 'wonderland': 33,
 'sea': 34,
 'diving': 35}

In [5]:
tokenizer.word_counts

OrderedDict([('war', 1),
             ('against', 1),
             ('corruption', 1),
             ('be', 2),
             ('healthy', 1),
             ('fit', 1),
             ('achieve', 1),
             ('uprise', 1),
             ('your', 1),
             ('career', 1),
             ('holiday', 1),
             ('vacation', 1),
             ('in', 4),
             ('los', 1),
             ('angeles', 1),
             ('good', 1),
             ('reputed', 1),
             ('job', 1),
             ('international', 1),
             ('company', 1),
             ('travelling', 1),
             ('yacht', 1),
             ('fifa', 1),
             ('wc', 1),
             ('final', 1),
             ('earn', 1),
             ('high', 1),
             ('scale', 1),
             ('visit', 1),
             ('to', 1),
             ('7', 1),
             ('wonderland', 1),
             ('sea', 1),
             ('diving', 1)])

In [6]:
tokenizer.document_count

10

In [7]:
from tensorflow.keras.preprocessing.text import one_hot
vocabSize = 50
encodedReviews = [one_hot(d, vocabSize) for d in texts]
print(f'encoded reviews: {encodedReviews}')

encoded reviews: [[46, 46, 29], [38, 46, 38, 19], [26, 31, 7, 30], [39, 36, 19, 34, 46], [35, 48, 43, 19, 23, 21], [40, 19, 39], [27, 15, 4], [3, 19, 11, 25], [1, 16, 7, 48], [43, 24]]


In [8]:
sequences =  tokenizer.texts_to_sequences(texts)
sequences

[[4, 5, 6],
 [3, 7, 3, 8],
 [9, 10, 11, 12],
 [13, 14, 2, 15, 16],
 [17, 18, 19, 2, 20, 21],
 [22, 2, 23],
 [24, 25, 26],
 [27, 2, 28, 29],
 [30, 31, 32, 33],
 [34, 35]]

In [9]:
from keras.utils import pad_sequences

In [10]:
sequences = pad_sequences(sequences, padding = 'post')
sequences

array([[ 4,  5,  6,  0,  0,  0],
       [ 3,  7,  3,  8,  0,  0],
       [ 9, 10, 11, 12,  0,  0],
       [13, 14,  2, 15, 16,  0],
       [17, 18, 19,  2, 20, 21],
       [22,  2, 23,  0,  0,  0],
       [24, 25, 26,  0,  0,  0],
       [27,  2, 28, 29,  0,  0],
       [30, 31, 32, 33,  0,  0],
       [34, 35,  0,  0,  0,  0]], dtype=int32)

In [11]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

model = Sequential()

model.add(Embedding (input_dim = vocabSize, output_dim = 2, input_length = 6))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 6, 2)              100       
                                                                 
Total params: 100
Trainable params: 100
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile('adam', 'accuracy')

In [13]:
prediction = model.predict(sequences)
print(prediction)

1/1 [==============================] - 0s 161ms/step
[[[ 0.00753665  0.03444559]
  [-0.02369142 -0.02231668]
  [ 0.04047069 -0.03010173]
  [ 0.0481825   0.04400075]
  [ 0.0481825   0.04400075]
  [ 0.0481825   0.04400075]]

 [[ 0.02053881  0.00779808]
  [ 0.02665906  0.02197025]
  [ 0.02053881  0.00779808]
  [ 0.0010466   0.00193071]
  [ 0.0481825   0.04400075]
  [ 0.0481825   0.04400075]]

 [[ 0.01554118  0.04550883]
  [-0.02990947 -0.02333772]
  [ 0.03469923 -0.02401106]
  [-0.03658714  0.03451279]
  [ 0.0481825   0.04400075]
  [ 0.0481825   0.04400075]]

 [[ 0.04578986  0.03931122]
  [-0.0218902   0.0401674 ]
  [-0.04526423 -0.02985914]
  [ 0.0362086  -0.01050887]
  [-0.01877437  0.01363296]
  [ 0.0481825   0.04400075]]

 [[ 0.02797139 -0.04495469]
  [ 0.01076145 -0.03567027]
  [-0.04237112 -0.00759109]
  [-0.04526423 -0.02985914]
  [-0.01295905 -0.03851029]
  [-0.02664861 -0.00353043]]

 [[ 0.01345855  0.0260121 ]
  [-0.04526423 -0.02985914]
  [-0.03394248  0.03409955]
  [ 0.0481825