In [ ]:
import  numpy as ny

texts = ["War Against Corruption", "Be Healthy Be Fit", "Achieve & uprise your career", "Holiday vacation in Los Angeles", "Good reputed job in international company",
        "Travelling in yacht", "Fifa wc final", "Earn in high scale", "Visit to 7 wonderland", "sea diving"]

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token = "winner")

In [ ]:
tokenizer.fit_on_texts(texts)

In [ ]:
tokenizer.word_index

{'winner': 1,
 'in': 2,
 'be': 3,
 'war': 4,
 'against': 5,
 'corruption': 6,
 'healthy': 7,
 'fit': 8,
 'achieve': 9,
 'uprise': 10,
 'your': 11,
 'career': 12,
 'holiday': 13,
 'vacation': 14,
 'los': 15,
 'angeles': 16,
 'good': 17,
 'reputed': 18,
 'job': 19,
 'international': 20,
 'company': 21,
 'travelling': 22,
 'yacht': 23,
 'fifa': 24,
 'wc': 25,
 'final': 26,
 'earn': 27,
 'high': 28,
 'scale': 29,
 'visit': 30,
 'to': 31,
 '7': 32,
 'wonderland': 33,
 'sea': 34,
 'diving': 35}

In [ ]:
tokenizer.word_counts

OrderedDict([('war', 1),
             ('against', 1),
             ('corruption', 1),
             ('be', 2),
             ('healthy', 1),
             ('fit', 1),
             ('achieve', 1),
             ('uprise', 1),
             ('your', 1),
             ('career', 1),
             ('holiday', 1),
             ('vacation', 1),
             ('in', 4),
             ('los', 1),
             ('angeles', 1),
             ('good', 1),
             ('reputed', 1),
             ('job', 1),
             ('international', 1),
             ('company', 1),
             ('travelling', 1),
             ('yacht', 1),
             ('fifa', 1),
             ('wc', 1),
             ('final', 1),
             ('earn', 1),
             ('high', 1),
             ('scale', 1),
             ('visit', 1),
             ('to', 1),
             ('7', 1),
             ('wonderland', 1),
             ('sea', 1),
             ('diving', 1)])

In [ ]:
tokenizer.document_count

10

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
vocabSize = 50
encodedReviews = [one_hot(d, vocabSize) for d in texts]
print(f'encoded reviews: {encodedReviews}')

encoded reviews: [[11, 19, 8], [4, 16, 4, 19], [36, 43, 28, 27], [43, 16, 10, 5, 45], [30, 3, 24, 10, 2, 29], [1, 10, 33], [41, 6, 12], [40, 10, 38, 12], [17, 15, 37, 20], [34, 27]]


In [ ]:
sequences =  tokenizer.texts_to_sequences(texts)
sequences

[[4, 5, 6],
 [3, 7, 3, 8],
 [9, 10, 11, 12],
 [13, 14, 2, 15, 16],
 [17, 18, 19, 2, 20, 21],
 [22, 2, 23],
 [24, 25, 26],
 [27, 2, 28, 29],
 [30, 31, 32, 33],
 [34, 35]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
sequences = pad_sequences(sequences, padding = 'post')
sequences

array([[ 4,  5,  6,  0,  0,  0],
       [ 3,  7,  3,  8,  0,  0],
       [ 9, 10, 11, 12,  0,  0],
       [13, 14,  2, 15, 16,  0],
       [17, 18, 19,  2, 20, 21],
       [22,  2, 23,  0,  0,  0],
       [24, 25, 26,  0,  0,  0],
       [27,  2, 28, 29,  0,  0],
       [30, 31, 32, 33,  0,  0],
       [34, 35,  0,  0,  0,  0]], dtype=int32)

In [ ]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

model = Sequential()

model.add(Embedding (input_dim = vocabSize, output_dim = 2, input_length = 6))

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 6, 2)              100       
                                                                 
Total params: 100
Trainable params: 100
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile('adam', 'accuracy')

In [ ]:
prediction = model.predict(sequences)
print(prediction)

1/1 [==============================] - 0s 42ms/step
[[[ 0.01188649  0.01904551]
  [ 0.02911432 -0.01401155]
  [ 0.00294492  0.03204092]
  [-0.00677357 -0.03399152]
  [-0.00677357 -0.03399152]
  [-0.00677357 -0.03399152]]

 [[-0.04837101  0.02399793]
  [ 0.02249921  0.03880804]
  [-0.04837101  0.02399793]
  [-0.04334613  0.01298679]
  [-0.00677357 -0.03399152]
  [-0.00677357 -0.03399152]]

 [[ 0.04631985  0.04665205]
  [ 0.00483931  0.00424946]
  [-0.03116106  0.01657105]
  [-0.03226541 -0.01538063]
  [-0.00677357 -0.03399152]
  [-0.00677357 -0.03399152]]

 [[ 0.0094568   0.02055055]
  [-0.03007001  0.00519091]
  [ 0.0476657  -0.0080393 ]
  [ 0.03533688  0.04231687]
  [ 0.00242958  0.01242157]
  [-0.00677357 -0.03399152]]

 [[ 0.0193341   0.02217455]
  [ 0.047385    0.04400566]
  [ 0.02654386  0.04658904]
  [ 0.0476657  -0.0080393 ]
  [-0.03975934  0.00339677]
  [ 0.03846495 -0.00319342]]

 [[-0.01515602 -0.0277765 ]
  [ 0.0476657  -0.0080393 ]
  [-0.00040513  0.00801969]
  [-0.00677357