In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as ny # linear algebra
import pandas as ps # data processing, CSV file I/O (e.g. pd.read_csv)

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
reviews = ['Nice Tone', 'Delicious Taste', 'Uprising the growth.', 'Just Loved It!', 'Improve Performance', 'Nice Movie', 'Scaring Movies', 'Dangerous Site', 'Poor Network', 'Consistency', 'Keep it up']
reactions = ny.array([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0 ])

In [3]:
one_hot('Improve Performance', 110)

[100, 82]

In [4]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[15, 19],
 [1, 14],
 [3, 22, 35],
 [4, 13, 26],
 [11, 34],
 [15, 6],
 [44, 9],
 [35, 5],
 [31, 32],
 [13],
 [6, 26, 6]]

In [5]:
max_length = 6
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
padded_reviews

array([[15, 19,  0,  0,  0,  0],
       [ 1, 14,  0,  0,  0,  0],
       [ 3, 22, 35,  0,  0,  0],
       [ 4, 13, 26,  0,  0,  0],
       [11, 34,  0,  0,  0,  0],
       [15,  6,  0,  0,  0,  0],
       [44,  9,  0,  0,  0,  0],
       [35,  5,  0,  0,  0,  0],
       [31, 32,  0,  0,  0,  0],
       [13,  0,  0,  0,  0,  0],
       [ 6, 26,  6,  0,  0,  0]], dtype=int32)

In [6]:
embeded_vector_size = 7

model = Sequential()
model.add(Embedding (vocab_size, embeded_vector_size, input_length = max_length, name = 'embedding'))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

2023-01-13 16:28:41.815412: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [7]:
x = padded_reviews
y = reactions

In [8]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 6, 7)              350       
_________________________________________________________________
flatten (Flatten)            (None, 42)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 43        
Total params: 393
Trainable params: 393
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(x, y, epochs = 50, verbose = True)

2023-01-13 16:28:42.180096: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/50
1/1 [==============================] - 1s 602ms/step - loss: 0.6901 - accuracy: 0.4545
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6885 - accuracy: 0.4545
Epoch 3/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6869 - accuracy: 0.6364
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6853 - accuracy: 0.8182
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6837 - accuracy: 0.8182
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6821 - accuracy: 0.8182
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6805 - accuracy: 0.7273
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6789 - accuracy: 0.7273
Epoch 9/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6773 - accuracy: 0.7273
Epoch 10/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6757 - accuracy: 0.7273
Epoch 11/50
1/1 [====================

In [10]:
loss, accuracy = model.evaluate(x, y)

1/1 [==============================] - 0s 155ms/step - loss: 0.5990 - accuracy: 0.6364


In [11]:
model.get_layer('embedding').get_weights()[0]

array([[-0.0563398 ,  0.08268891, -0.02360056, -0.04585864, -0.08938249,
        -0.09227523,  0.05138531],
       [-0.01933263, -0.06977939,  0.08279154,  0.00674054, -0.03944855,
         0.06139695, -0.05085038],
       [-0.0009595 ,  0.04703087,  0.03779485,  0.01911234, -0.02913919,
        -0.0418377 , -0.03889275],
       [-0.07177778, -0.00845541,  0.03693575, -0.05198101, -0.06714216,
         0.06421717, -0.04530367],
       [-0.01182459, -0.03412858,  0.08053918, -0.03089954, -0.07098647,
         0.08636339, -0.00422212],
       [ 0.09833763, -0.01917516,  0.04751537, -0.09136695,  0.09036987,
         0.07655812, -0.08848441],
       [-0.0432349 ,  0.03131451, -0.06016082,  0.03633051, -0.05066119,
        -0.01882611,  0.04551557],
       [-0.00149968,  0.00905162,  0.00317047,  0.03286017,  0.00223012,
        -0.00288258, -0.04871105],
       [ 0.0498344 ,  0.01443727, -0.01448501,  0.00134281, -0.00106042,
        -0.03111142,  0.0307786 ],
       [ 0.0218905 , -0.0412

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [13]:
weights[13]

array([-0.0697832 ,  0.07340927,  0.01356791,  0.04712225, -0.03909699,
        0.05235616,  0.08746585], dtype=float32)

In [14]:
weights[19]

array([-0.02132962,  0.00830755, -0.00195518,  0.07902769, -0.09944181,
       -0.00868874,  0.05185646], dtype=float32)